package com.smartbear;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2017-04-04T21:51:34.423+03:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://smartbear.com", name = "SampleWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SampleWebServiceSoap {

    /**
     * This method uses an object as a parameter.
     */
    @WebMethod(operationName = "SetSampleObject", action = "http://smartbear.com/SetSampleObject")
    @RequestWrapper(localName = "SetSampleObject", targetNamespace = "http://smartbear.com", className = "com.smartbear.SetSampleObject")
    @ResponseWrapper(localName = "SetSampleObjectResponse", targetNamespace = "http://smartbear.com", className = "com.smartbear.SetSampleObjectResponse")
    @WebResult(name = "SetSampleObjectResult", targetNamespace = "http://smartbear.com")
    public java.lang.String setSampleObject(
        @WebParam(name = "obj", targetNamespace = "http://smartbear.com")
        com.smartbear.SampleTestClass obj
    );

    /**
     * This method returns a string value.
     */
    @WebMethod(operationName = "HelloWorld", action = "http://smartbear.com/HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://smartbear.com", className = "com.smartbear.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://smartbear.com", className = "com.smartbear.HelloWorldResponse")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://smartbear.com")
    public java.lang.String helloWorld();

    /**
     * This method returns the current system time.
     */
    @WebMethod(operationName = "GetCurrentTime", action = "http://smartbear.com/GetCurrentTime")
    @RequestWrapper(localName = "GetCurrentTime", targetNamespace = "http://smartbear.com", className = "com.smartbear.GetCurrentTime")
    @ResponseWrapper(localName = "GetCurrentTimeResponse", targetNamespace = "http://smartbear.com", className = "com.smartbear.GetCurrentTimeResponse")
    @WebResult(name = "GetCurrentTimeResult", targetNamespace = "http://smartbear.com")
    public javax.xml.datatype.XMLGregorianCalendar getCurrentTime();

    /**
     * This method returns an array of integer values.
     */
    @WebMethod(operationName = "GetArray", action = "http://smartbear.com/GetArray")
    @RequestWrapper(localName = "GetArray", targetNamespace = "http://smartbear.com", className = "com.smartbear.GetArray")
    @ResponseWrapper(localName = "GetArrayResponse", targetNamespace = "http://smartbear.com", className = "com.smartbear.GetArrayResponse")
    @WebResult(name = "GetArrayResult", targetNamespace = "http://smartbear.com")
    public com.smartbear.ArrayOfInt getArray();

    /**
     * This method returns an object.
     */
    @WebMethod(operationName = "GetSampleObject", action = "http://smartbear.com/GetSampleObject")
    @RequestWrapper(localName = "GetSampleObject", targetNamespace = "http://smartbear.com", className = "com.smartbear.GetSampleObject")
    @ResponseWrapper(localName = "GetSampleObjectResponse", targetNamespace = "http://smartbear.com", className = "com.smartbear.GetSampleObjectResponse")
    @WebResult(name = "GetSampleObjectResult", targetNamespace = "http://smartbear.com")
    public com.smartbear.SampleTestClass getSampleObject(
        @WebParam(name = "no", targetNamespace = "http://smartbear.com")
        int no
    );

    /**
     * This method returns an object that is an XML node.
     */
    @WebMethod(operationName = "GetXmlData", action = "http://smartbear.com/GetXmlData")
    @RequestWrapper(localName = "GetXmlData", targetNamespace = "http://smartbear.com", className = "com.smartbear.GetXmlData")
    @ResponseWrapper(localName = "GetXmlDataResponse", targetNamespace = "http://smartbear.com", className = "com.smartbear.GetXmlDataResponse")
    @WebResult(name = "GetXmlDataResult", targetNamespace = "http://smartbear.com")
    public com.smartbear.GetXmlDataResponse.GetXmlDataResult getXmlData();
}
