drop table memes;


create table memes (
id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 0) NOT NULL PRIMARY KEY,
name varchar(64) not null,
type varchar(32),
year integer,
status varchar(16),
origin varchar(64),
badge varchar(32),
inserted TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

create table operations (
uuid varchar(36) not null,
operationid integer not null,
starttime timestamp default current_timestamp,
stoptime timestamp,
data varchar(64),
state integer
);

insert into memes (name, type, year, status, origin, badge) values 
('Lenny Face', 'Shitposting', 2012, 'Confirmed', 'Ylilauta', null), 
('Forever Alone', 'Character', 2010, 'Confirmed', 'FunnyJunk', null), 
('Dolan', 'Character', 2010, 'Confirmed', 'Kuvalauta / Finnish imageboard', 'NSFW'),
('Good Guy Greg', null, 2011, 'Confirmed', '4chan', null),
('Doge', 'Character', 2013, 'Confirmed', 'Tumblr', null),
('Pepe the Frog', 'Character', 2016, 'Confirmed', 'Boy''s Club', null);



select * from memes;